DROP TYPE IF EXISTS delivery_status CASCADE;
CREATE TYPE delivery_status AS ENUM ('NEW', 'IN_PROGRESS', 'DELIVERED');

DROP TABLE IF EXISTS shipment CASCADE;
CREATE TABLE IF NOT EXISTS shipment (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_id BIGINT,
weight DOUBLE PRECISION,
address_from VARCHAR(255),
address_to VARCHAR(255),
status delivery_status,
price DOUBLE PRECISION
);

DROP TABLE IF EXISTS customer CASCADE;
CREATE TABLE IF NOT EXISTS customer (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
country VARCHAR(255),
first_name VARCHAR(255),
last_name VARCHAR(255),
phone_number VARCHAR(255),
email VARCHAR(255)
);

DROP TABLE IF EXISTS event_publication CASCADE;
CREATE TABLE IF NOT EXISTS event_publication (
completion_date timestamp(6) with time zone,
publication_date timestamp(6) with time zone,
id uuid not null,
event_type varchar(255),
listener_id varchar(255),
serialized_event varchar(255),
primary key (id)
);
