DROP TABLE IF EXISTS address CASCADE;
CREATE TABLE IF NOT EXISTS address (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
city VARCHAR(255),
street VARCHAR(255),
house VARCHAR(255),
apartment VARCHAR(255),
zip_code VARCHAR(255)
);

DROP TYPE IF EXISTS delivery_status CASCADE;
CREATE TYPE delivery_status AS ENUM ('NEW', 'IN_PROGRESS', 'DELIVERED');

DROP TABLE IF EXISTS shipment CASCADE;
CREATE TABLE IF NOT EXISTS shipment (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
customer_id BIGINT,
weight DOUBLE PRECISION,
address_from_id BIGINT REFERENCES address(id),
address_to_id BIGINT REFERENCES address(id),
status delivery_status,
price DOUBLE PRECISION
);

DROP TABLE IF EXISTS customer CASCADE;
CREATE TABLE IF NOT EXISTS customer (
id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
first_name VARCHAR(255),
last_name VARCHAR(255),
phone_number BIGINT
);

DROP TABLE IF EXISTS event_publication CASCADE;
CREATE TABLE IF NOT EXISTS event_publication (
completion_date timestamp(6) with time zone,
publication_date timestamp(6) with time zone,
id uuid not null,
event_type varchar(255),
listener_id varchar(255),
serialized_event varchar(255),
primary key (id)
);
